listener 1883 0.0.0.0
allow_anonymous true
persistence false
log_type all

connection bridge-to-cloud-a
address cloud-a:1883
try_private false
topic fl/edge/updates/cloud_a/# out 0

connection bridge-to-cloud-b
address cloud-b:1883
try_private false
topic fl/edge/updates/cloud_b/# out 0
topic fl/cloud/control/# in 0
topic fl/cloud/global_model in 0
